import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import AppBar from "./components/AppBar";
import { Hammersmith_One } from "next/font/google";

const hone = Hammersmith_One({
  subsets: ['latin'],
  weight: '400'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Watch Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={hone.className}>
        <Providers>
          <AppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
